import Head from 'next/head'
import styles from '../../styles/Home.module.css'

function Blog({ post }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog: {post.title}
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/blog/[path].js</code>
        </p>

      </main>

    </div>
  )
}

export async function getStaticPaths() {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const posts = await res.json()

  return {
    paths: posts.map((post) => `/blog/${post.id}`) || [],
    fallback: true,
  }
}

// This also gets called at build time
export async function getStaticProps({ params }) {
  // params contains the post `id`.
  // If the route is like /posts/1, then params.id is 1
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?id=${params.path}`)
  const post = await res.json()

  // Pass post data to the page via props
  return { props: { post: post[0] } }
}

export default Blog