import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

function Blog({ posts }) {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      {posts.map((post) => (
        <Link href={`/blog/${post.id}`}>
          <a>
            <h2>{post.title}</h2>
            <p>{post.body}</p>
          </a>
        </Link>
      ))}
    </div>

    </div>
  )
}

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries. See the "Technical details" section.
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const posts = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts,
    },
  }
}

export default Blog